steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd Proyecto 1/proyecto1_jason_salazar/environments/$BRANCH_NAME/terraform
      terraform init -reconfigure
