steps:

- id: 'lint'
  name: 'python:3.8-slim'
  entrypoint: '/bin/sh'  
  args:
  - '-c'
  - | 
      cd Proyecto\ 1/proyecto1_jason_salazar/cloud_function
      pip install -r requirements.txt
      pip install pylint      
      pylint --errors-only  main.py

# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd Proyecto\ 1/proyecto1_jason_salazar/environments/$BRANCH_NAME/terraform
      terraform init -reconfigure
# [END tf-init]

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd Proyecto\ 1/proyecto1_jason_salazar/environments/$BRANCH_NAME/terraform
      terraform plan 
# [END tf-plan]