
steps:

- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      ls
      if [ -d "terraform/$dev/" ]; then
        cd terraform/$dev
        terraform init
      else
        for dir in Proyecto1/terraform/dev/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "############# SE HACE EL TERRAFORM INIT #############"
          echo "                                                     "
          echo "              Este se ejecuta en ${env}              "
          echo "-----------------------------------------------------"
          echo ""
          terraform init || exit 1
          cd ../../
        done
      fi 

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      ls
      if [ -d "terraform/$dev/" ]; then
        cd terraform/$dev
        terraform plan
      else
        for dir in Proyecto1/terraform/dev/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "############# SE HACE EL TERRAFORM PLAN #############"
          echo "                                                     "
          echo "              Este se ejecuta en ${env}              "
          echo "-----------------------------------------------------"
          echo ""
          terraform plan || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform/$dev/" ]; then
        cd terraform/$dev      
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]      
